### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by carloshs1994** [zhadier/My-Portofolio#11]
Hi Zeeshan! Nice work so far.
<img src="https://media4.giphy.com/media/9hc5Z9Ko56QCVmbwhq/giphy.gif"/>

But here are some changes you could implement.

- One of the buttons does not have the right size so you could consider changing it.
<img src="https://media0.giphy.com/media/w567xuOsFbYiwnTooE/giphy.gif"/>

**Comment by zhadier** [comment]
# Hey @carloshs1994  :high_brightness: 
#### Thank you so much for the amazing review:last_quarter_moon_with_face:, I've fixed the bug :smiley: :rice_cracker: 
<img src="https://media1.giphy.com/media/fsW2XJQYnmnaKV55eg/giphy.gif"/>
